version: 1.0.{build}
os: Unstable
platform: 
  - x64
environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
configuration:
  - Debug
  - Release
clone_folder: c:\projects\AppVeyorTest

before_build:
  - cmd: cd C:\projects\AppVeyorTest
  - cmd: md build
  - cmd: cd build
  - cmd: set CMAKE_GENERATOR_NAME=Visual Studio 14 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
build:
  project: C:\projects\AppVeyorTest\build\AppVeyorTest.sln # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: normal                         # MSBuild verbosity level (quiet|minimal|normal|detailed)