version: 1.0.{build}
os: Visual Studio 2015
platform: 
  - x64
environment:
  BOOST_ROOT: C:\dev\boost
  BOOST_LIBRARYDIR: C:\dev\boost\lib64-msvc-14.0
configuration:
  - Debug
  - Release
clone_folder: c:\projects\AppVeyorTest

install:
  - cd c:\dev
  - ps: Start-FileDownload 'http://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/boost_1_59_0-msvc-14.0-64.exe/download'
  - cmd: boost_1_59_0-msvc-14.0-64.exe /VERYSILENT /SUPPRESSMSGBOXES /DIR="c:\dev\boost"

before_build:
  - cmd: cd C:\projects\AppVeyorTest
  - cmd: md build
  - cmd: cd build
  - cmd: set CMAKE_GENERATOR_NAME=Visual Studio 14 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
build:
  project: C:\projects\dart\build\AppVeyorTest.sln # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: normal                         # MSBuild verbosity level (quiet|minimal|normal|detailed)